const PlayersData = [
  {
    name: "LeBron Raymone James",
    team: "Los Angeles Lakers",
    nationality: "American",
    jerseyNumber: 23,
    age: 38,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png",
  },
  {
    name: "Luka Dončić",
    team: "Dallas Mavericks",
    nationality: "Slovenian",
    jerseyNumber: null,
    age: 24,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png",
  },
  {
    name: "Wardell Stephen Curry II",
    team: "Golden State Warriors",
    nationality: "American",
    jerseyNumber: 30,
    age: 28,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201939.png",
  },
  {
    name: "Giannis Sina Ugo Antetokounmpo",
    team: "Milwaukee Bucks",
    nationality: "Greek",
    jerseyNumber: 34,
    age: 29,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png",
  },
  {
    name: "Anthony Davis",
    team: "Los Angeles Lakers",
    nationality: "American",
    jerseyNumber: 3,
    age: 28,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203076.png",
  },
  {
    name: "Kawhi Leonard",
    team: "LA Clippers",
    nationality: "American",
    jerseyNumber: 2,
    age: 30,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/202695.png",
  },
  {
    name: "Joel Embiid",
    team: "Philadelphia 76ers",
    nationality: "Cameroonian",
    jerseyNumber: 21,
    age: 28,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/203954.png",
  },
  {
    name: "Derrick Rose",
    team: "New York Knicks",
    nationality: "American",
    jerseyNumber: 4,
    age: 33,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/201565.png",
  },
  {
    name: "Jayson Tatum",
    team: "Boston Celtics",
    nationality: "American",
    jerseyNumber: 0,
    age: 23,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png",
  },
  {
    name: "Devin Booker",
    team: "Phoenix Suns",
    nationality: "American",
    jerseyNumber: 1,
    age: 25,
    image: "https://cdn.nba.com/headshots/nba/latest/1040x760/1626164.png",
  },
];
export default PlayersData;
//create data [{object in array}]
